name: Blockscout

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  skip-upstream-pipeline:
    name: Skip upstream-only jobs
    runs-on: ubuntu-latest
    steps:
      - run: echo "This fork skips Blockscout's upstream CI pipeline."
